#!/bin/bash

# email-cli Functional Test Runner
# Orchestrates mock server and client execution

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BIN_DIR="$PROJECT_ROOT/bin"
MOCK_SERVER_SRC="$PROJECT_ROOT/tests/functional/mock_imap_server.c"
MOCK_SERVER_BIN="$PROJECT_ROOT/build/tests/functional/mock_imap_server"
MOCK_SMTP_SRC="$PROJECT_ROOT/tests/pty/mock_smtp_server.c"
MOCK_SMTP_BIN="$PROJECT_ROOT/build/tests/functional/mock_smtp_server"

echo "--- email-cli Functional Tests ---"

# 0. Ensure test TLS certificates exist (generated by CMake build)
TEST_CERT="$PROJECT_ROOT/build/tests/certs/test.crt"
TEST_KEY="$PROJECT_ROOT/build/tests/certs/test.key"
if [ ! -f "$TEST_CERT" ] || [ ! -f "$TEST_KEY" ]; then
    echo "Generating test TLS certificates..."
    mkdir -p "$PROJECT_ROOT/build/tests/certs"
    openssl req -x509 -newkey rsa:2048 \
        -keyout "$TEST_KEY" \
        -out "$TEST_CERT" \
        -days 3650 -nodes \
        -subj "/CN=localhost"
fi

# 1. Compile Mock Servers (needs OpenSSL for TLS)
mkdir -p "$PROJECT_ROOT/build/tests/functional"
gcc "$MOCK_SERVER_SRC" -o "$MOCK_SERVER_BIN" -lssl -lcrypto
gcc "$MOCK_SMTP_SRC"   -o "$MOCK_SMTP_BIN"   -lssl -lcrypto

# 2. Start Mock IMAP Server in background
# Run from BUILD_DIR so that relative path "tests/certs/test.crt" resolves correctly
echo "Starting Mock IMAP Server..."
MOCK_LOG="$PROJECT_ROOT/build/tests/functional/mock_server.log"
(cd "$PROJECT_ROOT/build" && "$MOCK_SERVER_BIN") >"$MOCK_LOG" 2>&1 &
SERVER_PID=$!

# 2b. Start Mock SMTP Server in background
SMTP_PORT=9465
echo "Starting Mock SMTP Server on port $SMTP_PORT..."
SMTP_LOG="$PROJECT_ROOT/build/tests/functional/mock_smtp.log"
(cd "$PROJECT_ROOT/build" && MOCK_SMTP_PORT=$SMTP_PORT "$MOCK_SMTP_BIN") >"$SMTP_LOG" 2>&1 &
SMTP_PID=$!

# Ensure cleanup on exit
trap "kill $SERVER_PID $SMTP_PID 2>/dev/null || true" EXIT

# Give servers a moment to start
sleep 1

# 3. Create a temporary config for the test (IMAP + SMTP)
TEST_HOME="/tmp/email-cli-func-test"
rm -rf "$TEST_HOME"
mkdir -p "$TEST_HOME/.config/email-cli"
cat <<EOF > "$TEST_HOME/.config/email-cli/config.ini"
EMAIL_HOST=imaps://localhost:9993
EMAIL_USER=testuser
EMAIL_PASS=testpass
EMAIL_FOLDER=INBOX
SSL_NO_VERIFY=1
SMTP_HOST=smtps://localhost:$SMTP_PORT
SMTP_USER=testuser
SMTP_PASS=testpass
EMAIL_SENT_FOLDER=Sent
EOF

export HOME="$TEST_HOME"
# Ensure XDG overrides do not redirect the binary to a different config/cache path
unset XDG_CONFIG_HOME XDG_CACHE_HOME

PASSED=0
FAILED=0

check() {
    local desc="$1"
    local pattern="$2"
    local output="$3"
    if echo "$output" | grep -q "$pattern"; then
        echo "  [PASS] $desc"
        PASSED=$((PASSED + 1))
    else
        echo "  [FAIL] $desc  (expected pattern: '$pattern')"
        FAILED=$((FAILED + 1))
    fi
}

check_not() {
    local desc="$1"
    local pattern="$2"
    local text="$3"
    if ! echo "$text" | grep -q "$pattern"; then
        echo "  [PASS] $desc"
        PASSED=$((PASSED + 1))
    else
        echo "  [FAIL] $desc  (unexpected pattern found: '$pattern')"
        FAILED=$((FAILED + 1))
    fi
}

# 4. Test: help (no args)
echo "Running: email-cli (no args) ..."
HELP_OUTPUT=$("$BIN_DIR/email-cli" 2>&1 || true)
echo "$HELP_OUTPUT"
echo "--- Help Assertions ---"
check "General help: list cmd"    "list"                    "$HELP_OUTPUT"
check "General help: show cmd"    "show"                    "$HELP_OUTPUT"
check "General help: help cmd"    "help"                    "$HELP_OUTPUT"

# 5. Test: help list
echo ""
HELP_LIST=$("$BIN_DIR/email-cli" help list 2>&1)
echo "--- help list ---"
check "help list: usage line"     "email-cli list"          "$HELP_LIST"

# 6. Test: help show
HELP_SHOW=$("$BIN_DIR/email-cli" help show 2>&1)
echo "--- help show ---"
check "help show: usage line"     "email-cli show"          "$HELP_SHOW"

# 7. Test: list
echo ""
echo "Running: email-cli list ..."
LIST_OUTPUT=$("$BIN_DIR/email-cli" list 2>&1 || true)
echo "$LIST_OUTPUT"
echo "--- List Assertions ---"
check "Message count shown"       "message(s) in"           "$LIST_OUTPUT"
check "Unread count shown"        "unread"                  "$LIST_OUTPUT"
check "Table separator shown"     "═══"                     "$LIST_OUTPUT"
check "Subject in table"          "Test Message"            "$LIST_OUTPUT"

# 8. Test: list --all (same behavior — all messages always shown)
echo ""
echo "Running: email-cli list --all ..."
ALL_OUTPUT=$("$BIN_DIR/email-cli" list --all 2>&1 || true)
echo "$ALL_OUTPUT"
echo "--- List --all Assertions ---"
check "All mode: message count"   "message(s) in"           "$ALL_OUTPUT"
check "All mode: unread count"    "unread"                  "$ALL_OUTPUT"
check "All mode: subject shown"   "Test Message"            "$ALL_OUTPUT"

# 9. Test: list --folder
echo ""
echo "Running: email-cli list --folder INBOX ..."
FOLDER_OUTPUT=$("$BIN_DIR/email-cli" list --folder INBOX 2>&1 || true)
check "Folder override used"      "INBOX"                   "$FOLDER_OUTPUT"

# 10. Test: show command
echo ""
echo "Running: email-cli show 1 ..."
SHOW_OUTPUT=$("$BIN_DIR/email-cli" show 1 2>&1 || true)
echo "$SHOW_OUTPUT"
echo "--- Show Assertions ---"
check "From header shown"         "From:"                   "$SHOW_OUTPUT"
check "Subject header shown"      "Subject:"                "$SHOW_OUTPUT"
check "Email body shown"          "Hello from Mock Server"  "$SHOW_OUTPUT"
check_not "Show: no CSS in output (color)"     "color"      "$SHOW_OUTPUT"
check_not "Show: no CSS in output (font-size)" "font-size"  "$SHOW_OUTPUT"

# 11. Test: folders (flat)
echo ""
echo "Running: email-cli folders ..."
FOLDERS_OUTPUT=$("$BIN_DIR/email-cli" folders 2>&1 || true)
echo "$FOLDERS_OUTPUT"
echo "--- Folders Assertions ---"
check "Folders: INBOX listed"     "INBOX"                   "$FOLDERS_OUTPUT"
check "Folders: subfolder listed" "INBOX.Sent"              "$FOLDERS_OUTPUT"

# 12. Test: folders --tree
echo ""
echo "Running: email-cli folders --tree ..."
TREE_OUTPUT=$("$BIN_DIR/email-cli" folders --tree 2>&1 || true)
echo "$TREE_OUTPUT"
echo "--- Folders Tree Assertions ---"
check "Tree: has branch char"     "──"                      "$TREE_OUTPUT"
check "Tree: INBOX shown"         "INBOX"                   "$TREE_OUTPUT"
check "Tree: Sent shown"          "Sent"                    "$TREE_OUTPUT"

# 13. Test: empty folder (batch mode)
echo ""
echo "Running: email-cli list --folder INBOX.Empty --batch ..."
EMPTY_OUTPUT=$("$BIN_DIR/email-cli" list --folder INBOX.Empty --batch 2>&1 || true)
echo "$EMPTY_OUTPUT"
echo "--- Empty folder assertions ---"
check "Empty folder: no messages msg" "No messages"  "$EMPTY_OUTPUT"

# CRITICAL: verify email-cli never issued a STORE (flag-modification) command
MOCK_CMDS=$(cat "$MOCK_LOG" 2>/dev/null || true)
echo ""
echo "--- CRITICAL: Read-only guarantee (no STORE commands issued) ---"
check_not "No STORE command sent to server" "STORE" "$MOCK_CMDS"
echo "(mock server log: $MOCK_LOG)"

# REGRESSION: read_response use-after-free — LOGIN must never fail against a
# server that actually returns OK.  Check both the client output and the log.
SESSION_LOG="$TEST_HOME/.cache/email-cli/logs/session.log"
SESSION=$(cat "$SESSION_LOG" 2>/dev/null || true)
echo ""
echo "--- REGRESSION: read_response use-after-free (LOGIN must not fail on OK) ---"
check_not "No 'LOGIN failed' in list output"   "LOGIN failed" "$LIST_OUTPUT"
check_not "No 'LOGIN failed' in show output"   "LOGIN failed" "$SHOW_OUTPUT"
check_not "No 'LOGIN failed' in session log"   "LOGIN failed" "$SESSION"
check     "Session log shows 'Logged in' or authenticated" \
          "authenticated\|Logged in\|LOGIN completed" "$SESSION"

# Count line: reverse-video marker and sync indicator
CACHE_DIR="$TEST_HOME/.cache/email-cli"
PID_FILE="$CACHE_DIR/sync.pid"
echo ""
echo "--- Count line / sync indicator ---"

# Without pid file: no spurious "syncing"
rm -f "$PID_FILE"
NO_SYNC_OUTPUT=$("$BIN_DIR/email-cli" list --batch 2>&1 || true)
check     "Count line present (no-sync)"     "message(s) in"  "$NO_SYNC_OUTPUT"
check_not "No spurious syncing (no pid file)" "syncing"        "$NO_SYNC_OUTPUT"

# With a stale pid file (nonexistent PID): still no "syncing"
mkdir -p "$CACHE_DIR"
echo "999999" > "$PID_FILE"
STALE_OUTPUT=$("$BIN_DIR/email-cli" list --batch 2>&1 || true)
check_not "No spurious syncing (stale pid)"   "syncing"        "$STALE_OUTPUT"
rm -f "$PID_FILE"

# CRITICAL: send + save-to-Sent (IMAP APPEND LITERAL+)
# This test covers the full compose → SMTP send → IMAP APPEND path.
# A regression here means the Sent folder save is broken (e.g. TLS buffering hang).
echo ""
echo "--- CRITICAL: send + save-to-Sent (IMAP APPEND via LITERAL+) ---"
echo "Running: email-tui --batch send ..."
SEND_OUTPUT=$("$BIN_DIR/email-tui" --batch send \
    --to "recipient@test.example.com" \
    --subject "Functional Test Mail" \
    --body "Hello from functional test." \
    2>&1 || true)
echo "$SEND_OUTPUT"
check "Send: message sent confirmation"  "Message sent"  "$SEND_OUTPUT"
check "Send: saved-to-Sent confirmation" "Saved"         "$SEND_OUTPUT"

# Verify the SMTP mock received the message
SMTP_LOG_CONTENT=$(cat "$SMTP_LOG" 2>/dev/null || true)
check "SMTP mock: RECEIVED confirmation" "RECEIVED" "$SMTP_LOG_CONTENT"

# Verify the IMAP client issued an APPEND command (email-tui logs to tui-session.log)
TUI_LOG="$TEST_HOME/.cache/email-cli/logs/tui-session.log"
TUI_SESSION=$(cat "$TUI_LOG" 2>/dev/null || true)
check "TUI session log: APPEND command issued to IMAP server" "APPEND" "$TUI_SESSION"

echo ""
echo "--- Functional Test Results ---"
echo "Passed: $PASSED / $((PASSED + FAILED))"

if [ "$FAILED" -gt 0 ]; then
    echo "FUNCTIONAL TEST FAILED"
    exit 1
fi

echo "Functional test complete."
