#!/bin/bash

# email-cli Functional Test Runner
# Tests account isolation, CLI correctness, and multi-account scenarios.

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BIN_DIR="$PROJECT_ROOT/bin"
MOCK_SERVER_SRC="$PROJECT_ROOT/tests/functional/mock_imap_server.c"
MOCK_SERVER_BIN="$PROJECT_ROOT/build/tests/functional/mock_imap_server"
MOCK_SMTP_SRC="$PROJECT_ROOT/tests/pty/mock_smtp_server.c"
MOCK_SMTP_BIN="$PROJECT_ROOT/build/tests/functional/mock_smtp_server"
MOCK_GMAIL_SRC="$PROJECT_ROOT/tests/functional/mock_gmail_api_server.c"
MOCK_GMAIL_BIN="$PROJECT_ROOT/build/tests/functional/mock_gmail_api_server"

echo "--- email-cli Functional Tests ---"

# 0. TLS certificates (generated by CMake build)
TEST_CERT="$PROJECT_ROOT/build/tests/certs/test.crt"
TEST_KEY="$PROJECT_ROOT/build/tests/certs/test.key"
if [ ! -f "$TEST_CERT" ] || [ ! -f "$TEST_KEY" ]; then
    echo "Generating test TLS certificates..."
    mkdir -p "$PROJECT_ROOT/build/tests/certs"
    openssl req -x509 -newkey rsa:2048 \
        -keyout "$TEST_KEY" -out "$TEST_CERT" \
        -days 3650 -nodes -subj "/CN=localhost"
fi

# 1. Compile mock servers
mkdir -p "$PROJECT_ROOT/build/tests/functional"
gcc "$MOCK_SERVER_SRC" -o "$MOCK_SERVER_BIN" -lssl -lcrypto
gcc "$MOCK_SMTP_SRC"   -o "$MOCK_SMTP_BIN"   -lssl -lcrypto
gcc "$MOCK_GMAIL_SRC"  -o "$MOCK_GMAIL_BIN"

# Kill any lingering mock server instances from a previous (interrupted) run
# before binding to the same ports again.
pkill -f "mock_imap_server" 2>/dev/null || true
pkill -f "mock_smtp_server" 2>/dev/null || true
sleep 0.3

# 2. Start three independent mock IMAP servers on separate ports.
#    Each serves a distinct subject so cross-account cache contamination is detectable.
#    Servers run from BUILD_DIR so "tests/certs/test.crt" resolves correctly.

echo "Starting mock IMAP server 1 (port 9993, subject: AlphaAccountMsg)..."
MOCK_LOG1="$PROJECT_ROOT/build/tests/functional/mock_server1.log"
(cd "$PROJECT_ROOT/build" && MOCK_IMAP_PORT=9993 MOCK_IMAP_SUBJECT="AlphaAccountMsg" \
    "$MOCK_SERVER_BIN") >"$MOCK_LOG1" 2>&1 &
SERVER1_PID=$!

echo "Starting mock IMAP server 2 (port 9994, subject: BetaAccountMsg)..."
MOCK_LOG2="$PROJECT_ROOT/build/tests/functional/mock_server2.log"
(cd "$PROJECT_ROOT/build" && MOCK_IMAP_PORT=9994 MOCK_IMAP_SUBJECT="BetaAccountMsg" \
    "$MOCK_SERVER_BIN") >"$MOCK_LOG2" 2>&1 &
SERVER2_PID=$!

echo "Starting mock IMAP server 3 (port 9995, subject: GammaAccountMsg)..."
MOCK_LOG3="$PROJECT_ROOT/build/tests/functional/mock_server3.log"
(cd "$PROJECT_ROOT/build" && MOCK_IMAP_PORT=9995 MOCK_IMAP_SUBJECT="GammaAccountMsg" \
    "$MOCK_SERVER_BIN") >"$MOCK_LOG3" 2>&1 &
SERVER3_PID=$!

SMTP_PORT=9465
echo "Starting mock SMTP server (port $SMTP_PORT)..."
SMTP_LOG="$PROJECT_ROOT/build/tests/functional/mock_smtp.log"
(cd "$PROJECT_ROOT/build" && MOCK_SMTP_PORT=$SMTP_PORT \
    "$MOCK_SMTP_BIN") >"$SMTP_LOG" 2>&1 &
SMTP_PID=$!

trap "kill $SERVER1_PID $SERVER2_PID $SERVER3_PID $SMTP_PID \
          \${SERVER200_PID:-} \${GMAIL_SERVER_PID:-} 2>/dev/null || true" EXIT

sleep 1

# ── Test helpers ─────────────────────────────────────────────────────────────

PASSED=0
FAILED=0

check() {
    local desc="$1" pattern="$2" output="$3"
    if echo "$output" | grep -q "$pattern"; then
        echo "  [PASS] $desc"
        PASSED=$((PASSED + 1))
    else
        echo "  [FAIL] $desc  (expected pattern: '$pattern')"
        echo "         actual: $(echo "$output" | head -3 | tr '\n' '|')"
        FAILED=$((FAILED + 1))
    fi
}

check_not() {
    local desc="$1" pattern="$2" text="$3"
    if ! echo "$text" | grep -q "$pattern"; then
        echo "  [PASS] $desc"
        PASSED=$((PASSED + 1))
    else
        echo "  [FAIL] $desc  (unexpected pattern found: '$pattern')"
        echo "         actual: $(echo "$text" | grep "$pattern" | head -2 | tr '\n' '|')"
        FAILED=$((FAILED + 1))
    fi
}

# Create an isolated HOME directory with one account config.
#   make_home <home_path> <email_address> <imap_port>
make_home() {
    local home="$1" email="$2" port="$3"
    rm -rf "$home"
    mkdir -p "$home/.config/email-cli/accounts/$email"
    cat > "$home/.config/email-cli/accounts/$email/config.ini" <<CONFIG
EMAIL_HOST=imaps://localhost:$port
EMAIL_USER=$email
EMAIL_PASS=testpass
EMAIL_FOLDER=INBOX
EMAIL_SENT_FOLDER=INBOX.Sent
SSL_NO_VERIFY=1
SMTP_HOST=smtps://localhost:$SMTP_PORT
SMTP_USER=$email
SMTP_PASS=testpass
CONFIG
}

# Add a second account config to an existing HOME directory.
#   add_account <home_path> <email_address> <imap_port>
add_account() {
    local home="$1" email="$2" port="$3"
    mkdir -p "$home/.config/email-cli/accounts/$email"
    cat > "$home/.config/email-cli/accounts/$email/config.ini" <<CONFIG
EMAIL_HOST=imaps://localhost:$port
EMAIL_USER=$email
EMAIL_PASS=testpass
EMAIL_FOLDER=INBOX
EMAIL_SENT_FOLDER=INBOX.Sent
SSL_NO_VERIFY=1
CONFIG
}

# Run `email-cli list --batch [--folder F]` with the given HOME and optional
# shared XDG_DATA_HOME; returns stdout+stderr combined.
run_list() {
    local home="$1" data_home="$2" folder="${3:-INBOX}"
    local args=("--batch" "list")
    [ "$folder" != "INBOX" ] && args+=("--folder" "$folder")
    (export HOME="$home"
     [ -n "$data_home" ] && export XDG_DATA_HOME="$data_home" || unset XDG_DATA_HOME
     unset XDG_CONFIG_HOME XDG_CACHE_HOME
     "$BIN_DIR/email-cli" "${args[@]}" 2>&1 || true)
}

# Run `email-cli <account> list` — explicit account selection (multi-account homes).
run_list_as() {
    local account="$1" home="$2" data_home="$3" folder="${4:-INBOX}"
    local args=("$account" "--batch" "list")
    [ "$folder" != "INBOX" ] && args+=("--folder" "$folder")
    (export HOME="$home"
     [ -n "$data_home" ] && export XDG_DATA_HOME="$data_home" || unset XDG_DATA_HOME
     unset XDG_CONFIG_HOME XDG_CACHE_HOME
     "$BIN_DIR/email-cli" "${args[@]}" 2>&1 || true)
}

# Run `email-cli show <uid>` with the given HOME and optional XDG_DATA_HOME.
run_show() {
    local home="$1" data_home="$2" uid="${3:-1}"
    (export HOME="$home"
     [ -n "$data_home" ] && export XDG_DATA_HOME="$data_home" || unset XDG_DATA_HOME
     unset XDG_CONFIG_HOME XDG_CACHE_HOME
     "$BIN_DIR/email-cli" show "$uid" 2>&1 || true)
}

# Run `email-cli folders` with the given HOME.
run_folders() {
    local home="$1" data_home="$2" extra="${3:-}"
    (export HOME="$home"
     [ -n "$data_home" ] && export XDG_DATA_HOME="$data_home" || unset XDG_DATA_HOME
     unset XDG_CONFIG_HOME XDG_CACHE_HOME
     # shellcheck disable=SC2086
     "$BIN_DIR/email-cli" list-folders $extra 2>&1 || true)
}

# ── Account fixtures ──────────────────────────────────────────────────────────
#
#  Three accounts on three independent servers:
#    alpha@test.local  →  server 9993  →  subject "AlphaAccountMsg"
#    beta@test.local   →  server 9994  →  subject "BetaAccountMsg"
#    gamma@test.local  →  server 9995  →  subject "GammaAccountMsg"
#
#  Alphabetical order: alpha < beta < gamma
#  (used by config_load_from_store and config_list_accounts)

ALPHA="alpha@test.local"
BETA="beta@test.local"
GAMMA="gamma@test.local"

H_ALPHA="/tmp/email-cli-ft-alpha"    # single-account home for alpha
H_BETA="/tmp/email-cli-ft-beta"      # single-account home for beta
H_GAMMA="/tmp/email-cli-ft-gamma"    # single-account home for gamma
H_AB="/tmp/email-cli-ft-ab"          # alpha + beta  (alpha first alphabetically)
H_BG="/tmp/email-cli-ft-bg"          # beta  + gamma (beta first alphabetically)
H_ALL="/tmp/email-cli-ft-all"        # all three      (alpha first alphabetically)

SHARED="/tmp/email-cli-ft-shared"    # shared XDG_DATA_HOME for isolation tests

make_home "$H_ALPHA" "$ALPHA" 9993
make_home "$H_BETA"  "$BETA"  9994
make_home "$H_GAMMA" "$GAMMA" 9995

make_home "$H_AB" "$ALPHA" 9993; add_account "$H_AB" "$BETA"  9994
make_home "$H_BG" "$BETA"  9994; add_account "$H_BG" "$GAMMA" 9995

make_home "$H_ALL" "$ALPHA" 9993
add_account "$H_ALL" "$BETA"  9994
add_account "$H_ALL" "$GAMMA" 9995

# ════════════════════════════════════════════════════════════════════════════
# Phase 1 — Basic single-account CLI
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 1: Basic single-account CLI ---"

# 1.1 help
HELP=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME; \
         "$BIN_DIR/email-cli" 2>&1 || true) )
check "1.1 help: list cmd mentioned"     "list"           "$HELP"
check "1.1 help: show cmd mentioned"     "show"           "$HELP"
check "1.1 help: folders cmd mentioned"  "list-folders"        "$HELP"

HELP_LIST=$( (export HOME="$H_ALPHA"; "$BIN_DIR/email-cli" help list 2>&1 || true) )
check "1.2 help list: usage line"        "email-cli list" "$HELP_LIST"

HELP_SHOW=$( (export HOME="$H_ALPHA"; "$BIN_DIR/email-cli" help show 2>&1 || true) )
check "1.3 help show: usage line"        "email-cli show" "$HELP_SHOW"

# 1.2 list
L1=$(run_list "$H_ALPHA" "")
check "1.4 list: message count shown"       "message(s) in"  "$L1"
check "1.5 list: unread count shown"        "unread"         "$L1"
check "1.6 list: subject shown"             "AlphaAccountMsg" "$L1"
check "1.7 list: account email in header"   "$ALPHA"         "$L1"
check "1.8 list: table separator"           "═══"            "$L1"

# 1.3 show
S1=$(run_show "$H_ALPHA" "")
check "1.9  show: From header"              "From:"          "$S1"
check "1.10 show: Subject header"           "Subject:"       "$S1"
check "1.11 show: body text present"        "Hello from Mock" "$S1"
check_not "1.12 show: no raw CSS (color)"   "color"          "$S1"
check_not "1.13 show: no raw CSS (font)"    "font-size"      "$S1"

# 1.4 folders
F1=$(run_folders "$H_ALPHA" "")
check "1.14 folders: INBOX listed"          "INBOX"          "$F1"
check "1.15 folders: subfolder listed"      "INBOX.Sent"     "$F1"

FTREE=$(run_folders "$H_ALPHA" "" "--tree")
check "1.16 folders --tree: branch char"    "──"             "$FTREE"
check "1.17 folders --tree: INBOX shown"    "INBOX"          "$FTREE"

# 1.5 empty folder
EMPTY=$(run_list "$H_ALPHA" "" "INBOX.Empty")
check "1.18 empty folder: no messages"      "No messages"    "$EMPTY"

# 1.6 explicit folder override
OVERRIDE=$(run_list "$H_ALPHA" "" "INBOX.Sent")
check "1.19 list --folder: Sent shown"      "INBOX.Sent\|message(s) in" "$OVERRIDE"

# 1.7 read-only guarantee: list must never issue STORE
check_not "1.20 list: no STORE sent to server" "STORE" "$(cat "$MOCK_LOG1")"

# 1.8 login regression
SESSION1="$H_ALPHA/.cache/email-cli/logs/session.log"
SESS1=$(cat "$SESSION1" 2>/dev/null || true)
check_not "1.21 no LOGIN failed in output"  "LOGIN failed"   "$L1"
check     "1.22 LOGIN completed in session" "LOGIN completed\|authenticated" "$SESS1"

# ════════════════════════════════════════════════════════════════════════════
# Phase 2 — Warm cache: second run uses cached manifest
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 2: Warm cache (second run) ---"

L1W=$(run_list "$H_ALPHA" "")
check "2.1 warm: own subject still shown"  "AlphaAccountMsg"  "$L1W"
check "2.2 warm: own account header"       "$ALPHA"           "$L1W"
check_not "2.3 warm: no beta subject"      "BetaAccountMsg"   "$L1W"
check_not "2.4 warm: no gamma subject"     "GammaAccountMsg"  "$L1W"

# ════════════════════════════════════════════════════════════════════════════
# Phase 3 — Fresh isolation: three accounts, one shared data dir
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 3: Fresh multi-account isolation (shared data dir) ---"

rm -rf "$SHARED"

# 3.1 alpha — first run, shared data dir empty
A3=$(run_list "$H_ALPHA" "$SHARED")
check "3.1 alpha fresh: own subject"        "AlphaAccountMsg"  "$A3"
check "3.2 alpha fresh: own email header"   "$ALPHA"           "$A3"
check_not "3.3 alpha fresh: no beta"        "BetaAccountMsg"   "$A3"
check_not "3.4 alpha fresh: no gamma"       "GammaAccountMsg"  "$A3"

STORE_A="$SHARED/email-cli/accounts/$ALPHA"
check "3.5 alpha local store dir created"   "." "$(test -d "$STORE_A"   && echo ok || echo missing)"
check "3.6 alpha manifest created"          "." "$(test -f "$STORE_A/manifests/INBOX.tsv" && echo ok || echo missing)"

# 3.2 beta — alpha's cache exists, beta is empty → must fetch from server 2
B3=$(run_list "$H_BETA" "$SHARED")
check "3.7 beta fresh: own subject"         "BetaAccountMsg"   "$B3"
check "3.8 beta fresh: own email header"    "$BETA"            "$B3"
check_not "3.9 beta fresh: no alpha cached" "AlphaAccountMsg"  "$B3"
check_not "3.10 beta fresh: no gamma"       "GammaAccountMsg"  "$B3"

STORE_B="$SHARED/email-cli/accounts/$BETA"
check "3.11 beta: own local store dir"      "." "$(test -d "$STORE_B"   && echo ok || echo missing)"
check "3.12 beta: manifest separate"        "." "$(test -f "$STORE_B/manifests/INBOX.tsv" && echo ok || echo missing)"
check "3.13 beta+alpha stores are distinct" "." "$([ "$STORE_A" != "$STORE_B" ] && echo ok || echo same)"

# 3.3 gamma — alpha+beta both cached
G3=$(run_list "$H_GAMMA" "$SHARED")
check "3.14 gamma fresh: own subject"       "GammaAccountMsg"  "$G3"
check "3.15 gamma fresh: own email header"  "$GAMMA"           "$G3"
check_not "3.16 gamma fresh: no alpha"      "AlphaAccountMsg"  "$G3"
check_not "3.17 gamma fresh: no beta"       "BetaAccountMsg"   "$G3"

STORE_G="$SHARED/email-cli/accounts/$GAMMA"
check "3.18 gamma: own local store dir"     "." "$(test -d "$STORE_G"   && echo ok || echo missing)"

# ════════════════════════════════════════════════════════════════════════════
# Phase 4 — Warm cache isolation: re-run after all caches are populated
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 4: Warm cache isolation (all caches populated) ---"

# All three manifests now exist in $SHARED. Each account re-run must still
# return ITS OWN data and not another account's cached manifest.

A4=$(run_list "$H_ALPHA" "$SHARED")
check "4.1 alpha warm: own subject"         "AlphaAccountMsg"  "$A4"
check "4.2 alpha warm: own header"          "$ALPHA"           "$A4"
check_not "4.3 alpha warm: no beta leak"    "BetaAccountMsg"   "$A4"
check_not "4.4 alpha warm: no gamma leak"   "GammaAccountMsg"  "$A4"

B4=$(run_list "$H_BETA" "$SHARED")
check "4.5 beta warm: own subject"          "BetaAccountMsg"   "$B4"
check "4.6 beta warm: own header"           "$BETA"            "$B4"
check_not "4.7 beta warm: no alpha leak"    "AlphaAccountMsg"  "$B4"
check_not "4.8 beta warm: no gamma leak"    "GammaAccountMsg"  "$B4"

G4=$(run_list "$H_GAMMA" "$SHARED")
check "4.9 gamma warm: own subject"         "GammaAccountMsg"  "$G4"
check "4.10 gamma warm: own header"         "$GAMMA"           "$G4"
check_not "4.11 gamma warm: no alpha leak"  "AlphaAccountMsg"  "$G4"
check_not "4.12 gamma warm: no beta leak"   "BetaAccountMsg"   "$G4"

# ════════════════════════════════════════════════════════════════════════════
# Phase 5 — Two-account HOME: config_load_from_store picks alphabetically first
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 5: Two-account HOME (alphabetical first wins) ---"

rm -rf "$SHARED"

# 5.1 H_AB has alpha + beta; explicitly select alpha → must show alpha, not beta.
run_list "$H_BETA" "$SHARED" >/dev/null 2>&1 || true   # beta cache now warm

AB_OUT=$(run_list_as "$ALPHA" "$H_AB" "$SHARED")
check "5.1 AB home: select alpha (own subject)"   "AlphaAccountMsg"  "$AB_OUT"
check "5.2 AB home: alpha email in header"        "$ALPHA"           "$AB_OUT"
check_not "5.3 AB home: beta NOT shown"           "BetaAccountMsg"   "$AB_OUT"

# 5.2 Also warm alpha cache, re-run H_AB → still alpha
run_list "$H_ALPHA" "$SHARED" >/dev/null 2>&1 || true

AB_OUT2=$(run_list_as "$ALPHA" "$H_AB" "$SHARED")
check "5.4 AB home warm: alpha unchanged"         "AlphaAccountMsg"  "$AB_OUT2"
check_not "5.5 AB home warm: beta still absent"   "BetaAccountMsg"   "$AB_OUT2"

# 5.3 H_BG has beta + gamma; explicitly select beta → must show beta, not gamma.
run_list "$H_GAMMA" "$SHARED" >/dev/null 2>&1 || true

BG_OUT=$(run_list_as "$BETA" "$H_BG" "$SHARED")
check "5.6 BG home: select beta (own subject)"    "BetaAccountMsg"   "$BG_OUT"
check "5.7 BG home: beta email in header"         "$BETA"            "$BG_OUT"
check_not "5.8 BG home: gamma NOT shown"          "GammaAccountMsg"  "$BG_OUT"

# ════════════════════════════════════════════════════════════════════════════
# Phase 6 — Folder-specific isolation (Sent, Trash, Empty)
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 6: Folder-specific isolation ---"

rm -rf "$SHARED"

# 6.1 INBOX.Sent — each account sees its own content
AS=$(run_list "$H_ALPHA" "$SHARED" "INBOX.Sent")
check "6.1 alpha Sent: own subject"         "AlphaAccountMsg"  "$AS"
check "6.2 alpha Sent: own header"          "$ALPHA"           "$AS"

BS=$(run_list "$H_BETA" "$SHARED" "INBOX.Sent")
check "6.3 beta Sent: own subject"          "BetaAccountMsg"   "$BS"
check "6.4 beta Sent: own header"           "$BETA"            "$BS"
check_not "6.5 beta Sent: no alpha cached"  "AlphaAccountMsg"  "$BS"

GS=$(run_list "$H_GAMMA" "$SHARED" "INBOX.Sent")
check "6.6 gamma Sent: own subject"         "GammaAccountMsg"  "$GS"
check_not "6.7 gamma Sent: no alpha"        "AlphaAccountMsg"  "$GS"
check_not "6.8 gamma Sent: no beta"         "BetaAccountMsg"   "$GS"

# 6.2 INBOX.Trash — same isolation
AT=$(run_list "$H_ALPHA" "$SHARED" "INBOX.Trash")
check "6.9 alpha Trash: own subject"        "AlphaAccountMsg"  "$AT"

BT=$(run_list "$H_BETA" "$SHARED" "INBOX.Trash")
check "6.10 beta Trash: own subject"        "BetaAccountMsg"   "$BT"
check_not "6.11 beta Trash: no alpha"       "AlphaAccountMsg"  "$BT"

# 6.3 INBOX.Empty — always 0 messages, for all accounts
AE=$(run_list "$H_ALPHA" "$SHARED" "INBOX.Empty")
check "6.12 alpha Empty: no messages"       "No messages"      "$AE"

BE=$(run_list "$H_BETA" "$SHARED" "INBOX.Empty")
check "6.13 beta Empty: no messages"        "No messages"      "$BE"

GE=$(run_list "$H_GAMMA" "$SHARED" "INBOX.Empty")
check "6.14 gamma Empty: no messages"       "No messages"      "$GE"

# ════════════════════════════════════════════════════════════════════════════
# Phase 7 — show command isolation
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 7: show command isolation ---"

rm -rf "$SHARED"

# 7.1 Fresh show: alpha
SA=$(run_show "$H_ALPHA" "$SHARED")
check "7.1 alpha show: own subject in body" "AlphaAccountMsg"  "$SA"
check "7.2 alpha show: From header"         "From:"            "$SA"
check "7.3 alpha show: body present"        "Hello from Mock"  "$SA"
check_not "7.4 alpha show: no beta"         "BetaAccountMsg"   "$SA"

# 7.2 Warm alpha, fresh beta
run_list "$H_ALPHA" "$SHARED" >/dev/null 2>&1 || true

SB=$(run_show "$H_BETA" "$SHARED")
check "7.5 beta show (alpha cached): own"   "BetaAccountMsg"   "$SB"
check_not "7.6 beta show: no alpha"         "AlphaAccountMsg"  "$SB"

# 7.3 Warm both, show gamma
run_list "$H_BETA" "$SHARED" >/dev/null 2>&1 || true

SG=$(run_show "$H_GAMMA" "$SHARED")
check "7.7 gamma show (all cached): own"    "GammaAccountMsg"  "$SG"
check_not "7.8 gamma show: no alpha"        "AlphaAccountMsg"  "$SG"
check_not "7.9 gamma show: no beta"         "BetaAccountMsg"   "$SG"

# ════════════════════════════════════════════════════════════════════════════
# Phase 8 — Alternating runs: simulate rapid account switching
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 8: Alternating account runs (3 rounds) ---"

rm -rf "$SHARED"

for ROUND in 1 2 3; do
    RA=$(run_list "$H_ALPHA" "$SHARED")
    check "8.A round $ROUND: alpha own subject"   "AlphaAccountMsg"  "$RA"
    check_not "8.A round $ROUND: no beta leak"    "BetaAccountMsg"   "$RA"
    check_not "8.A round $ROUND: no gamma leak"   "GammaAccountMsg"  "$RA"

    RB=$(run_list "$H_BETA" "$SHARED")
    check "8.B round $ROUND: beta own subject"    "BetaAccountMsg"   "$RB"
    check_not "8.B round $ROUND: no alpha leak"   "AlphaAccountMsg"  "$RB"
    check_not "8.B round $ROUND: no gamma leak"   "GammaAccountMsg"  "$RB"

    RG=$(run_list "$H_GAMMA" "$SHARED")
    check "8.G round $ROUND: gamma own subject"   "GammaAccountMsg"  "$RG"
    check_not "8.G round $ROUND: no alpha leak"   "AlphaAccountMsg"  "$RG"
    check_not "8.G round $ROUND: no beta leak"    "BetaAccountMsg"   "$RG"
done

# ════════════════════════════════════════════════════════════════════════════
# Phase 9 — Manifest file content inspection
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 9: Manifest file content inspection ---"

rm -rf "$SHARED"
run_list "$H_ALPHA" "$SHARED" >/dev/null 2>&1 || true
run_list "$H_BETA"  "$SHARED" >/dev/null 2>&1 || true
run_list "$H_GAMMA" "$SHARED" >/dev/null 2>&1 || true

MA="$SHARED/email-cli/accounts/$ALPHA/manifests/INBOX.tsv"
MB="$SHARED/email-cli/accounts/$BETA/manifests/INBOX.tsv"
MG="$SHARED/email-cli/accounts/$GAMMA/manifests/INBOX.tsv"

check "9.1 alpha manifest exists"             "." "$(test -f "$MA" && echo ok || echo missing)"
check "9.2 beta manifest exists"              "." "$(test -f "$MB" && echo ok || echo missing)"
check "9.3 gamma manifest exists"             "." "$(test -f "$MG" && echo ok || echo missing)"

MA_CONTENT=$(cat "$MA" 2>/dev/null || true)
MB_CONTENT=$(cat "$MB" 2>/dev/null || true)
MG_CONTENT=$(cat "$MG" 2>/dev/null || true)

check "9.4 alpha manifest: own subject"        "AlphaAccountMsg"  "$MA_CONTENT"
check_not "9.5 alpha manifest: no beta"        "BetaAccountMsg"   "$MA_CONTENT"
check_not "9.6 alpha manifest: no gamma"       "GammaAccountMsg"  "$MA_CONTENT"

check "9.7 beta manifest: own subject"         "BetaAccountMsg"   "$MB_CONTENT"
check_not "9.8 beta manifest: no alpha"        "AlphaAccountMsg"  "$MB_CONTENT"
check_not "9.9 beta manifest: no gamma"        "GammaAccountMsg"  "$MB_CONTENT"

check "9.10 gamma manifest: own subject"       "GammaAccountMsg"  "$MG_CONTENT"
check_not "9.11 gamma manifest: no alpha"      "AlphaAccountMsg"  "$MG_CONTENT"
check_not "9.12 gamma manifest: no beta"       "BetaAccountMsg"   "$MG_CONTENT"

check "9.13 manifests are in distinct paths"   "." \
    "$([ "$MA" != "$MB" ] && [ "$MB" != "$MG" ] && [ "$MA" != "$MG" ] && echo ok || echo overlap)"

# Header cache files must also be separate
HDR_A="$SHARED/email-cli/accounts/$ALPHA/headers"
HDR_B="$SHARED/email-cli/accounts/$BETA/headers"
HDR_G="$SHARED/email-cli/accounts/$GAMMA/headers"
check "9.14 alpha header cache dir exists"     "." "$(test -d "$HDR_A" && echo ok || echo missing)"
check "9.15 beta header cache dir exists"      "." "$(test -d "$HDR_B" && echo ok || echo missing)"
check "9.16 gamma header cache dir exists"     "." "$(test -d "$HDR_G" && echo ok || echo missing)"
check "9.17 header dirs are distinct"          "." \
    "$([ "$HDR_A" != "$HDR_B" ] && [ "$HDR_B" != "$HDR_G" ] && echo ok || echo overlap)"

# ════════════════════════════════════════════════════════════════════════════
# Phase 10 — All-account HOME: list returns alphabetically-first account
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 10: Three-account HOME (alpha alphabetically first) ---"

rm -rf "$SHARED"

# Pre-populate gamma and beta caches so cross-contamination is detectable
run_list "$H_GAMMA" "$SHARED" >/dev/null 2>&1 || true
run_list "$H_BETA"  "$SHARED" >/dev/null 2>&1 || true

# H_ALL has alpha+beta+gamma; explicitly select alpha → must show alpha only
ALL_OUT=$(run_list_as "$ALPHA" "$H_ALL" "$SHARED")
check "10.1 all-home: select alpha (own subj)" "AlphaAccountMsg"  "$ALL_OUT"
check "10.2 all-home: alpha email in header"   "$ALPHA"           "$ALL_OUT"
check_not "10.3 all-home: no beta leaked"      "BetaAccountMsg"   "$ALL_OUT"
check_not "10.4 all-home: no gamma leaked"     "GammaAccountMsg"  "$ALL_OUT"

# Now populate alpha and re-run → still alpha
run_list "$H_ALPHA" "$SHARED" >/dev/null 2>&1 || true

ALL_OUT2=$(run_list_as "$ALPHA" "$H_ALL" "$SHARED")
check "10.5 all-home warm: alpha unchanged"    "AlphaAccountMsg"  "$ALL_OUT2"
check_not "10.6 all-home warm: no beta"        "BetaAccountMsg"   "$ALL_OUT2"
check_not "10.7 all-home warm: no gamma"       "GammaAccountMsg"  "$ALL_OUT2"

# ════════════════════════════════════════════════════════════════════════════
# Phase 11 — SMTP send + IMAP APPEND
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 11: SMTP send ---"

SEND_OUT=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" --batch send \
        --to "recipient@example.com" \
        --subject "Functional Test Mail" \
        --body "Hello from functional test." \
        2>&1 || true) )
check "11.1 send: message sent confirmation"    "Message sent"  "$SEND_OUT"
check "11.2 send: saved-to-Sent confirmation"   "Saved"         "$SEND_OUT"

SMTP_CONTENT=$(cat "$SMTP_LOG" 2>/dev/null || true)
check "11.3 SMTP mock: RECEIVED confirmation"   "RECEIVED"      "$SMTP_CONTENT"

CLI_LOG="$H_ALPHA/.cache/email-cli/logs/session.log"
CLI_CONTENT=$(cat "$CLI_LOG" 2>/dev/null || true)
check "11.4 IMAP APPEND command issued"         "APPEND"        "$CLI_CONTENT"

# ════════════════════════════════════════════════════════════════════════════
# Phase 12 — Sync pid-file indicator
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 12: sync pid-file indicator ---"

CACHE_DIR="$H_ALPHA/.cache/email-cli"
PID_FILE="$CACHE_DIR/sync.pid"

# No pid file → count line present, no "syncing" word
rm -f "$PID_FILE"
NO_SYNC=$(run_list "$H_ALPHA" "")
check     "12.1 no pid file: count line present"    "message(s) in"  "$NO_SYNC"
check_not "12.2 no pid file: no spurious 'syncing'" "syncing"        "$NO_SYNC"

# Stale pid file (nonexistent PID 999999) → still no "syncing"
mkdir -p "$CACHE_DIR"
echo "999999" > "$PID_FILE"
STALE=$(run_list "$H_ALPHA" "")
check_not "12.3 stale pid: no spurious 'syncing'"   "syncing"        "$STALE"
rm -f "$PID_FILE"

# ════════════════════════════════════════════════════════════════════════════
# Phase 13 — list --all mode
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 13: list --all mode ---"
ALL_LIST=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-cli" --batch list --all 2>&1 || true) )
check "13.1 list --all: message count"      "message"        "$ALL_LIST"
check "13.2 list --all: own subject shown"  "AlphaAccountMsg" "$ALL_LIST"

# ════════════════════════════════════════════════════════════════════════════
# Phase 14 — attachments command
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 14: attachments command ---"
# Use UID=1 (the UID the mock server serves)
ATTACH_OUT=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-cli" --batch list-attachments 1 2>&1 || true) )
check "14.1 attachments: notes.txt listed"  "notes.txt"  "$ATTACH_OUT"
check "14.2 attachments: data.bin listed"   "data.bin"   "$ATTACH_OUT"

# ════════════════════════════════════════════════════════════════════════════
# Phase 15 — save-attachment command
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 15: save-attachment command ---"
SAVE_DIR="/tmp/email-cli-ft-attach-$$"
mkdir -p "$SAVE_DIR"
SAVE_OUT=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-cli" --batch save-attachment 1 notes.txt "$SAVE_DIR" 2>&1 || true) )
check "15.1 save-attachment: saved confirmation"  "aved\|uccessful\|notes" "$SAVE_OUT"
check "15.2 save-attachment: file exists"  "." "$(test -f "$SAVE_DIR/notes.txt" && echo ok || echo missing)"
rm -rf "$SAVE_DIR"

# ════════════════════════════════════════════════════════════════════════════
# Phase 16 — mark-read and mark-unread
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 16: mark-read / mark-unread ---"
MARKR=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-cli" --batch mark-read 1 2>&1 || true) )
# Should not error
check_not "16.1 mark-read: no error"  "Error\|error\|failed" "$MARKR"

MARKUR=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-cli" --batch mark-unread 1 2>&1 || true) )
check_not "16.2 mark-unread: no error"  "Error\|error\|failed" "$MARKUR"

# ════════════════════════════════════════════════════════════════════════════
# Phase 17 — mark-starred and remove-starred
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 17: mark-starred / remove-starred ---"
STARS=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-cli" --batch mark-starred 1 2>&1 || true) )
check_not "17.1 mark-starred: no error"  "Error\|error\|failed" "$STARS"

UNSTAR=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-cli" --batch remove-starred 1 2>&1 || true) )
check_not "17.2 remove-starred: no error"  "Error\|error\|failed" "$UNSTAR"

# ════════════════════════════════════════════════════════════════════════════
# Phase 18 — list-accounts command
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 18: list-accounts command ---"
ACCS=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-cli" --batch list-accounts 2>&1 || true) )
check "18.1 list-accounts: account listed"  "alpha@test.local"  "$ACCS"
check "18.2 list-accounts: IMAP type"       "IMAP"              "$ACCS"

# ════════════════════════════════════════════════════════════════════════════
# Phase 19 — config show
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 19: config show ---"
CONF=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-cli" --batch config show 2>&1 || true) )
check "19.1 config show: host shown"   "localhost"         "$CONF"
check "19.2 config show: user shown"   "alpha@test.local"  "$CONF"
check_not "19.3 config show: pass masked"  "testpass"      "$CONF"

# ════════════════════════════════════════════════════════════════════════════
# Phase 20 — sync output format check
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 20: sync output format ---"
SYNC_OUT=$( (export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME;
    "$BIN_DIR/email-sync" 2>&1 || true) )
# The summary line must NOT have digits immediately after "stored" (old bug: "stored66")
check_not "20.1 sync output: no garbage after stored"  "stored[0-9]"  "$SYNC_OUT"
check "20.2 sync: fetched/stored line present"  "fetched.*stored\|already stored"  "$SYNC_OUT"

# ════════════════════════════════════════════════════════════════════════════
# Phase 21 — help for various topics
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 21: help topics ---"
HATT=$( (export HOME="$H_ALPHA"; "$BIN_DIR/email-cli" help list-attachments 2>&1 || true) )
check "21.1 help attachments: usage line"  "list-attachments"  "$HATT"

HSAVE=$( (export HOME="$H_ALPHA"; "$BIN_DIR/email-cli" help save-attachment 2>&1 || true) )
check "21.2 help save-attachment: usage"   "save-attachment"  "$HSAVE"

HSEND=$( (export HOME="$H_ALPHA"; "$BIN_DIR/email-cli" help send 2>&1 || true) )
check "21.3 help send: usage line"         "send"   "$HSEND"

HCONF=$( (export HOME="$H_ALPHA"; "$BIN_DIR/email-cli" help config 2>&1 || true) )
check "21.4 help config: usage line"       "config"  "$HCONF"

# ════════════════════════════════════════════════════════════════════════════
# Phase 22 — Credential obfuscation
#
# User Stories:
#   US-01  Default: fresh account config is saved with "enc:" prefix
#   US-02  Encrypted config loads and authenticates successfully
#   US-03  Plaintext config (legacy / obfuscation disabled) loads correctly
#   US-04  migrate-credentials converts plaintext → encrypted
#   US-05  Disable obfuscation + migrate converts encrypted → plaintext
#   US-06  Re-enable obfuscation + migrate converts plaintext → encrypted again
#   US-07  Two accounts with the same password produce different enc: values
#   US-08  migrate-credentials is idempotent (double-run safe)
#   US-09  Absent settings.ini defaults to obfuscation ON
#   US-10  Auto-encrypt on load (no migrate needed): plain→enc on first access
#   US-11  Auto-decrypt on load (no migrate needed): enc→plain on first access
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 22: credential obfuscation ---"

# Isolated home for obfuscation tests (no mock server needed for format checks)
H_CRED="$PROJECT_ROOT/build/tests/functional/cred_home"
CRED_EMAIL="cred@test.local"
CRED_CFG="$H_CRED/.config/email-cli/accounts/$CRED_EMAIL/config.ini"
CRED_SETTINGS="$H_CRED/.config/email-cli/settings.ini"

# Helper: write a plaintext account config
make_cred_home() {
    rm -rf "$H_CRED"
    mkdir -p "$H_CRED/.config/email-cli/accounts/$CRED_EMAIL"
    cat > "$CRED_CFG" <<CFG
EMAIL_HOST=imaps://localhost:9993
EMAIL_USER=$CRED_EMAIL
EMAIL_PASS=testpass
EMAIL_FOLDER=INBOX
SSL_NO_VERIFY=1
CFG
}

# Helper: run email-cli with isolated HOME (no server contact needed for migration)
run_cred() {
    (export HOME="$H_CRED"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
     "$BIN_DIR/email-cli" "$@" 2>&1 || true)
}

# ── US-09: No settings.ini → obfuscation defaults to ON ──────────────────
make_cred_home
# run migrate-credentials without a settings.ini
OUT_09=$(run_cred migrate-credentials)
check "22-US09: migrate without settings.ini reports encrypting" \
    "encrypt" "$OUT_09"
check "22-US09: config file has enc: prefix after default migrate" \
    "enc:" "$(cat "$CRED_CFG")"

# ── US-01: Default save produces enc: prefix ─────────────────────────────
# After migrate with default settings, the password field must have enc:
check "22-US01: EMAIL_PASS stored with enc: prefix" \
    "^EMAIL_PASS=enc:" "$(grep EMAIL_PASS "$CRED_CFG")"

# ── US-08: migrate-credentials is idempotent ─────────────────────────────
PASS_AFTER_FIRST=$(grep EMAIL_PASS "$CRED_CFG")
run_cred migrate-credentials > /dev/null
PASS_AFTER_SECOND=$(grep EMAIL_PASS "$CRED_CFG")
# The enc: prefix must still be present; the value may differ (new IV each time)
check "22-US08: idempotent — enc: still present after second migrate" \
    "^EMAIL_PASS=enc:" "$(grep EMAIL_PASS "$CRED_CFG")"

# ── US-02: Encrypted config loads and authenticates ──────────────────────
# Use the encrypted config to list emails via the mock IMAP server
OUT_02=$(run_list "$H_CRED" "" INBOX)
check "22-US02: encrypted config: list succeeds (AlphaAccountMsg)" \
    "AlphaAccountMsg" "$OUT_02"

# ── US-03: Plaintext config loads transparently ──────────────────────────
make_cred_home   # reset to plaintext
OUT_03=$(run_list "$H_CRED" "" INBOX)
check "22-US03: plaintext config: list succeeds (AlphaAccountMsg)" \
    "AlphaAccountMsg" "$OUT_03"

# ── US-04: migrate-credentials converts plaintext → encrypted ────────────
make_cred_home
# Confirm it is plaintext before migration
check_not "22-US04: before migrate — no enc: prefix" \
    "enc:" "$(cat "$CRED_CFG")"
run_cred migrate-credentials > /dev/null
check "22-US04: after migrate — enc: prefix present" \
    "enc:" "$(cat "$CRED_CFG")"
# And it must still authenticate
OUT_04=$(run_list "$H_CRED" "" INBOX)
check "22-US04: after migrate — list still works" \
    "AlphaAccountMsg" "$OUT_04"

# ── US-05: Disable obfuscation + migrate converts encrypted → plaintext ──
# Start from an encrypted config
make_cred_home
run_cred migrate-credentials > /dev/null
check "22-US05 setup: config is encrypted" \
    "enc:" "$(cat "$CRED_CFG")"
# Disable obfuscation
echo "credential_obfuscation=false" > "$CRED_SETTINGS"
OUT_05=$(run_cred migrate-credentials)
check "22-US05: migrate after disable reports removing encryption" \
    "plaintext" "$OUT_05"
check_not "22-US05: config no longer has enc: prefix" \
    "enc:" "$(cat "$CRED_CFG")"
check "22-US05: plaintext config still has the password value" \
    "EMAIL_PASS=testpass" "$(cat "$CRED_CFG")"
# Verify authentication still works
OUT_05b=$(run_list "$H_CRED" "" INBOX)
check "22-US05: after decrypt migrate — list still works" \
    "AlphaAccountMsg" "$OUT_05b"

# ── US-06: Re-enable obfuscation + migrate converts plaintext → encrypted ─
echo "credential_obfuscation=true" > "$CRED_SETTINGS"
run_cred migrate-credentials > /dev/null
check "22-US06: after re-enable — enc: prefix present again" \
    "enc:" "$(cat "$CRED_CFG")"
OUT_06=$(run_list "$H_CRED" "" INBOX)
check "22-US06: after re-encrypt — list still works" \
    "AlphaAccountMsg" "$OUT_06"

# ── US-07: Two accounts with the same password have different enc: values ─
H_DUAL="$PROJECT_ROOT/build/tests/functional/dual_home"
DUAL_A="dual-a@test.local"
DUAL_B="dual-b@test.local"
rm -rf "$H_DUAL"
for ACCT in "$DUAL_A" "$DUAL_B"; do
    mkdir -p "$H_DUAL/.config/email-cli/accounts/$ACCT"
    cat > "$H_DUAL/.config/email-cli/accounts/$ACCT/config.ini" <<CFG
EMAIL_HOST=imaps://localhost:9993
EMAIL_USER=$ACCT
EMAIL_PASS=samepassword
EMAIL_FOLDER=INBOX
SSL_NO_VERIFY=1
CFG
done
(export HOME="$H_DUAL"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
 "$BIN_DIR/email-cli" migrate-credentials 2>&1 || true) > /dev/null
ENC_A=$(grep EMAIL_PASS "$H_DUAL/.config/email-cli/accounts/$DUAL_A/config.ini")
ENC_B=$(grep EMAIL_PASS "$H_DUAL/.config/email-cli/accounts/$DUAL_B/config.ini")
check "22-US07: both accounts have enc: prefix" \
    "enc:" "$ENC_A"
check "22-US07: both accounts have enc: prefix (B)" \
    "enc:" "$ENC_B"
if [ "$ENC_A" = "$ENC_B" ]; then
    echo "  [FAIL] 22-US07: two accounts with same password produced identical enc: values"
    FAILED=$((FAILED + 1))
else
    echo "  [PASS] 22-US07: different accounts → different enc: values (even with same password)"
    PASSED=$((PASSED + 1))
fi

# ── US-10: Auto-encrypt on load (no migrate needed) ──────────────────────
# Start from a plaintext config with obfuscation ON (default)
make_cred_home
check_not "22-US10: before any access — no enc: prefix" \
    "enc:" "$(cat "$CRED_CFG")"
# A plain list command triggers load → auto-encrypt
run_list "$H_CRED" "" INBOX > /dev/null
check "22-US10: after first access — enc: prefix auto-applied" \
    "enc:" "$(cat "$CRED_CFG")"
# Authentication still works after auto-encrypt
OUT_10=$(run_list "$H_CRED" "" INBOX)
check "22-US10: after auto-encrypt — list still works" \
    "AlphaAccountMsg" "$OUT_10"

# ── US-11: Auto-decrypt on load (no migrate needed) ──────────────────────
# Start from an encrypted config, then disable obfuscation
make_cred_home
run_cred migrate-credentials > /dev/null  # encrypt first
check "22-US11 setup: config is encrypted" \
    "enc:" "$(cat "$CRED_CFG")"
echo "credential_obfuscation=false" > "$CRED_SETTINGS"
# A plain list command triggers load → auto-decrypt
run_list "$H_CRED" "" INBOX > /dev/null
check_not "22-US11: after first access — enc: prefix auto-removed" \
    "enc:" "$(cat "$CRED_CFG")"
check "22-US11: plaintext password restored in config" \
    "EMAIL_PASS=testpass" "$(cat "$CRED_CFG")"
# Authentication still works after auto-decrypt
OUT_11=$(run_list "$H_CRED" "" INBOX)
check "22-US11: after auto-decrypt — list still works" \
    "AlphaAccountMsg" "$OUT_11"

# Cleanup isolated homes
rm -rf "$H_CRED" "$H_DUAL"

# ════════════════════════════════════════════════════════════════════════════
# Phase 23 — Account selection on the command line
#
# User Stories:
#   US-01  Single account, no selector → works (backward compatible)
#   US-02  Multiple accounts + positional account arg → correct account used
#   US-03  Multiple accounts + --account flag → correct account used
#   US-04  Multiple accounts, no selector → helpful error listing accounts
#   US-05  email-cli-ro: positional account arg
#   US-06  email-cli-ro: --account flag
#   US-07  email-cli-ro: multiple accounts, no selector → error
#   US-08  Unknown account name → error
#   US-09  Positional account + help → shows help for command
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 23: account selection ---"

# ── US-01: Single account, no selector ───────────────────────────────────
OUT_23_01=$(run_list "$H_ALPHA" "")
check "23-US01: single account, no selector — AlphaAccountMsg" \
    "AlphaAccountMsg" "$OUT_23_01"

# ── US-02: Positional account arg in multi-account home ──────────────────
OUT_23_02A=$(
    export HOME="$H_AB"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" "$ALPHA" list --batch 2>&1 || true)
check "23-US02: positional alpha → AlphaAccountMsg" \
    "AlphaAccountMsg" "$OUT_23_02A"

OUT_23_02B=$(
    export HOME="$H_AB"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" "$BETA" list --batch 2>&1 || true)
check "23-US02: positional beta → BetaAccountMsg" \
    "BetaAccountMsg" "$OUT_23_02B"
check_not "23-US02: positional beta → not AlphaAccountMsg" \
    "AlphaAccountMsg" "$OUT_23_02B"

# ── US-03: --account flag in multi-account home ───────────────────────────
OUT_23_03=$(
    export HOME="$H_AB"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" --account "$BETA" list --batch 2>&1 || true)
check "23-US03: --account beta → BetaAccountMsg" \
    "BetaAccountMsg" "$OUT_23_03"

# ── US-04: Multiple accounts, no selector → error ────────────────────────
OUT_23_04=$(
    export HOME="$H_AB"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" list --batch 2>&1 || true)
check "23-US04: no selector error mentions alpha" \
    "$ALPHA" "$OUT_23_04"
check "23-US04: no selector error mentions beta" \
    "$BETA" "$OUT_23_04"

# ── US-05: email-cli-ro positional account ────────────────────────────────
OUT_23_05=$(
    export HOME="$H_AB"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli-ro" "$BETA" list --batch 2>&1 || true)
check "23-US05: email-cli-ro positional beta → BetaAccountMsg" \
    "BetaAccountMsg" "$OUT_23_05"

# ── US-06: email-cli-ro --account flag ────────────────────────────────────
OUT_23_06=$(
    export HOME="$H_AB"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli-ro" --account "$ALPHA" list --batch 2>&1 || true)
check "23-US06: email-cli-ro --account alpha → AlphaAccountMsg" \
    "AlphaAccountMsg" "$OUT_23_06"

# ── US-07: email-cli-ro multiple accounts, no selector → error ───────────
OUT_23_07=$(
    export HOME="$H_AB"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli-ro" list --batch 2>&1 || true)
check "23-US07: email-cli-ro no selector error mentions alpha" \
    "$ALPHA" "$OUT_23_07"

# ── US-08: Unknown account name → error ──────────────────────────────────
OUT_23_08=$(
    export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" "nobody@nowhere.invalid" list --batch 2>&1 || true)
check "23-US08: unknown account → error mentions account name" \
    "nobody@nowhere.invalid" "$OUT_23_08"

# ── US-09: Positional account + help shows command help ──────────────────
OUT_23_09=$(
    export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" "$ALPHA" help list 2>&1 || true)
check "23-US09: account + help list → shows list help" \
    "Usage:" "$OUT_23_09"

# ── US-10: list-accounts works without specifying an account ─────────────
OUT_23_10_ro=$(
    export HOME="$H_AB"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli-ro" list-accounts 2>&1 || true)
check "23-US10: email-cli-ro list-accounts lists alpha" \
    "$ALPHA" "$OUT_23_10_ro"
check "23-US10: email-cli-ro list-accounts lists beta" \
    "$BETA" "$OUT_23_10_ro"

OUT_23_10_rw=$(
    export HOME="$H_AB"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" list-accounts 2>&1 || true)
check "23-US10: email-cli list-accounts lists alpha" \
    "$ALPHA" "$OUT_23_10_rw"
check "23-US10: email-cli list-accounts lists beta" \
    "$BETA" "$OUT_23_10_rw"

# ════════════════════════════════════════════════════════════════════════════
# Phase 24 — --label alias and label name resolution
#
# User Stories:
#   US-01  --label is accepted as alias for --folder (IMAP mode)
#   US-02  email-cli-ro accepts --label alias (IMAP mode)
#   US-03  --label with unknown name falls back to using value as-is
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 24: --label alias ---"

# ── US-01: --label works as alias for --folder (IMAP) ─────────────────────
OUT_24_01_folder=$(run_list "$H_ALPHA" "" INBOX)
OUT_24_01_label=$(
    export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" list --batch --label INBOX 2>&1 || true)
check "24-US01: --label INBOX returns same as --folder INBOX" \
    "AlphaAccountMsg" "$OUT_24_01_label"

# ── US-02: email-cli-ro accepts --label alias ─────────────────────────────
OUT_24_02=$(
    export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli-ro" list --batch --label INBOX 2>&1 || true)
check "24-US02: email-cli-ro --label INBOX works" \
    "AlphaAccountMsg" "$OUT_24_02"

# ── US-03: --label with a name not in cache falls back gracefully ──────────
# (IMAP: an unknown label/folder returns empty or error, not a crash)
OUT_24_03=$(
    export HOME="$H_ALPHA"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
    "$BIN_DIR/email-cli" list --batch --label "NonExistentFolder" 2>&1 || true)
# Should not crash — either empty list or server error message
check_not "24-US03: unknown label does not crash (no segfault output)" \
    "Segmentation fault" "$OUT_24_03"

# ════════════════════════════════════════════════════════════════════════════
# Phase 25 — IMAP with 2 accounts (200 + 250 messages) + cross-contamination
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 25: IMAP with 2 accounts (200 + 250 messages) ---"

IMAP200_PORT=9996
IMAP250_PORT=9998
IMAP200_LOG="$PROJECT_ROOT/build/tests/functional/mock_server200.log"
IMAP250_LOG="$PROJECT_ROOT/build/tests/functional/mock_server250.log"
echo "Starting mock IMAP server A (port $IMAP200_PORT, 200 messages)..."
(cd "$PROJECT_ROOT/build" && MOCK_IMAP_PORT=$IMAP200_PORT MOCK_IMAP_COUNT=200 \
    MOCK_IMAP_MSG_PREFIX="IMapA-Message" \
    "$MOCK_SERVER_BIN") >"$IMAP200_LOG" 2>&1 &
SERVER200_PID=$!
echo "Starting mock IMAP server B (port $IMAP250_PORT, 250 messages)..."
(cd "$PROJECT_ROOT/build" && MOCK_IMAP_PORT=$IMAP250_PORT MOCK_IMAP_COUNT=250 \
    MOCK_IMAP_MSG_PREFIX="IMapB-Message" \
    "$MOCK_SERVER_BIN") >"$IMAP250_LOG" 2>&1 &
SERVER250_PID=$!
sleep 0.5

H_200="/tmp/email-cli-ft-200-$$"
ACCT200="imap200@test.local"
ACCT250="imap250@test.local"
rm -rf "$H_200"
mkdir -p "$H_200/.config/email-cli/accounts/$ACCT200"
mkdir -p "$H_200/.config/email-cli/accounts/$ACCT250"
cat > "$H_200/.config/email-cli/accounts/$ACCT200/config.ini" <<CFG200
EMAIL_HOST=imaps://localhost:$IMAP200_PORT
EMAIL_USER=$ACCT200
EMAIL_PASS=testpass
EMAIL_FOLDER=INBOX
EMAIL_SENT_FOLDER=INBOX.Sent
SSL_NO_VERIFY=1
CFG200
cat > "$H_200/.config/email-cli/accounts/$ACCT250/config.ini" <<CFG250
EMAIL_HOST=imaps://localhost:$IMAP250_PORT
EMAIL_USER=$ACCT250
EMAIL_PASS=testpass
EMAIL_FOLDER=INBOX
EMAIL_SENT_FOLDER=INBOX.Sent
SSL_NO_VERIFY=1
CFG250

run_200() {
    (export HOME="$H_200"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
     "$BIN_DIR/email-cli" "$ACCT200" "$@" 2>&1 || true)
}

run_250() {
    (export HOME="$H_200"; unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME
     "$BIN_DIR/email-cli" "$ACCT250" "$@" 2>&1 || true)
}

# ── IMAP-A (200 messages, prefix "IMapA-Message") ────────────────────────
# 25.1 list --all --limit 200
L200=$(run_200 --batch list --all --limit 200)
check "25.1 imap-A list: count line shows 200" "200" "$L200"

# 25.2 list with limit + offset
L200_off=$(run_200 --batch list --all --limit 10 --offset 1)
check "25.2 imap-A list --offset 1 --limit 10: shows messages" "IMapA" "$L200_off"

# 25.3 list with higher offset
L200_off2=$(run_200 --batch list --all --limit 10 --offset 101)
check "25.3 imap-A list --offset 101 --limit 10: shows messages" "IMapA" "$L200_off2"

# 25.4 show specific UIDs
S200_1=$(run_200 show 1)
check "25.4 imap-A show UID 1: subject shown" "IMapA-Message 1" "$S200_1"

S200_50=$(run_200 show 50)
check "25.5 imap-A show UID 50: subject shown" "IMapA-Message 50" "$S200_50"

S200_100=$(run_200 show 100)
check "25.6 imap-A show UID 100: subject shown" "IMapA-Message 100" "$S200_100"

# 25.7 Verify different UIDs show different subjects
check_not "25.7 imap-A show UID 50: not UID 1 subject" "IMapA-Message 1$" "$S200_50"
check_not "25.8 imap-A show UID 100: not UID 50 subject" "IMapA-Message 50$" "$S200_100"

# 25.9 list-attachments for UID with attachment (multiples of 10)
LA200=$(run_200 --batch list-attachments 10)
check "25.9 imap-A list-attachments UID 10: notes_10.txt listed" "notes_10" "$LA200"

# 25.10 list-attachments for UID without attachment
LA200_1=$(run_200 --batch list-attachments 1)
check_not "25.10 imap-A list-attachments UID 1: no notes_10.txt" "notes_10" "$LA200_1"

# 25.11 save-attachment
SAVE200_DIR="/tmp/email-cli-ft-attach200-$$"
mkdir -p "$SAVE200_DIR"
SA200=$(run_200 --batch save-attachment 10 notes_10.txt "$SAVE200_DIR")
check "25.11 imap-A save-attachment UID 10: confirmation" "aved\|uccessful\|notes" "$SA200"
check "25.12 imap-A save-attachment UID 10: file exists" "." \
    "$(test -f "$SAVE200_DIR/notes_10.txt" && echo ok || echo missing)"
rm -rf "$SAVE200_DIR"

# 25.13 list-folders
F200=$(run_200 list-folders)
check "25.13 imap-A list-folders: INBOX listed" "INBOX" "$F200"

# ── IMAP-B (250 messages, prefix "IMapB-Message") ────────────────────────
# 25.14 list all 250 messages
L250=$(run_250 --batch list --all --limit 250)
check "25.14 imap-B list: count line shows 250" "250" "$L250"

# 25.15 list offset
L250_off=$(run_250 --batch list --all --limit 10 --offset 201)
check "25.15 imap-B list --offset 201 --limit 10: shows messages" "IMapB" "$L250_off"

# 25.16 show UID 1
S250_1=$(run_250 show 1)
check "25.16 imap-B show UID 1: correct subject" "IMapB-Message 1" "$S250_1"

# 25.17 show UID 200
S250_200=$(run_250 show 200)
check "25.17 imap-B show UID 200: correct subject" "IMapB-Message 200" "$S250_200"

# 25.18 show UID 250
S250_250=$(run_250 show 250)
check "25.18 imap-B show UID 250: correct subject" "IMapB-Message 250" "$S250_250"

# 25.19 list-attachments UID 20 (multiple of 10)
LA250=$(run_250 --batch list-attachments 20)
check "25.19 imap-B list-attachments UID 20: notes_20.txt listed" "notes_20" "$LA250"

# 25.20 save-attachment
SAVE250_DIR="/tmp/email-cli-ft-attach250-$$"
mkdir -p "$SAVE250_DIR"
SA250=$(run_250 --batch save-attachment 20 notes_20.txt "$SAVE250_DIR")
check "25.20 imap-B save-attachment UID 20: confirmation" "aved\|uccessful\|notes" "$SA250"
check "25.21 imap-B save-attachment UID 20: file exists" "." \
    "$(test -f "$SAVE250_DIR/notes_20.txt" && echo ok || echo missing)"
rm -rf "$SAVE250_DIR"

# ── IMAP cross-contamination checks ──────────────────────────────────────
# 25.22 IMAP-A list must NOT contain IMAP-B subjects
check_not "25.22 imap-A list: no IMapB subjects" "IMapB" "$L200"

# 25.23 IMAP-B list must NOT contain IMAP-A subjects
check_not "25.23 imap-B list: no IMapA subjects" "IMapA" "$L250"

# 25.24 IMAP-A show must NOT contain IMAP-B subject text
check_not "25.24 imap-A show UID 1: no IMapB content" "IMapB" "$S200_1"

# 25.25 IMAP-B has 250 messages; IMAP-A must report 200 max
check_not "25.25 imap-A list: count not 250" "250 message" "$L200"

# ════════════════════════════════════════════════════════════════════════════
# Phase 26 — Gmail sync + offline list (2 accounts + cross-contamination)
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Phase 26: Gmail sync + offline list (2 accounts) ---"

GMAIL_PORT_A=9997
GMAIL_PORT_B=9999
GMAIL_LOG_A="$PROJECT_ROOT/build/tests/functional/mock_gmail_a.log"
GMAIL_LOG_B="$PROJECT_ROOT/build/tests/functional/mock_gmail_b.log"
echo "Starting mock Gmail API server A (port $GMAIL_PORT_A, 200 messages)..."
(MOCK_GMAIL_PORT=$GMAIL_PORT_A MOCK_GMAIL_COUNT=200 \
    MOCK_GMAIL_EMAIL="test@gmail.com" \
    "$MOCK_GMAIL_BIN") >"$GMAIL_LOG_A" 2>&1 &
GMAIL_SERVER_A_PID=$!
echo "Starting mock Gmail API server B (port $GMAIL_PORT_B, 150 messages)..."
(MOCK_GMAIL_PORT=$GMAIL_PORT_B MOCK_GMAIL_COUNT=150 \
    MOCK_GMAIL_EMAIL="test2@gmail.com" \
    MOCK_GMAIL_SUBJECT_PREFIX="GmailB-" \
    "$MOCK_GMAIL_BIN") >"$GMAIL_LOG_B" 2>&1 &
GMAIL_SERVER_B_PID=$!
sleep 0.5

# Shared temp home for both Gmail accounts (tests account isolation within one HOME)
H_GMAIL="/tmp/email-cli-ft-gmail-$$"
GMAIL_ACCT_A="test@gmail.com"
GMAIL_ACCT_B="test2@gmail.com"
rm -rf "$H_GMAIL"
mkdir -p "$H_GMAIL/config/email-cli/accounts/$GMAIL_ACCT_A"
mkdir -p "$H_GMAIL/config/email-cli/accounts/$GMAIL_ACCT_B"
mkdir -p "$H_GMAIL/data"
cat > "$H_GMAIL/config/email-cli/accounts/$GMAIL_ACCT_A/config.ini" <<GCFG_A
EMAIL_HOST=
EMAIL_USER=$GMAIL_ACCT_A
GMAIL_MODE=1
GMAIL_REFRESH_TOKEN=fakefaketoken
GCFG_A
cat > "$H_GMAIL/config/email-cli/accounts/$GMAIL_ACCT_B/config.ini" <<GCFG_B
EMAIL_HOST=
EMAIL_USER=$GMAIL_ACCT_B
GMAIL_MODE=1
GMAIL_REFRESH_TOKEN=fakefaketoken2
GCFG_B

# Helper: sync account A
run_gmail_sync_a() {
    (export XDG_CONFIG_HOME="$H_GMAIL/config"
     export XDG_DATA_HOME="$H_GMAIL/data"
     export XDG_CACHE_HOME="$H_GMAIL/cache"
     export HOME="$H_GMAIL"
     export GMAIL_TEST_TOKEN=testtoken
     export GMAIL_API_BASE_URL="http://localhost:$GMAIL_PORT_A/gmail/v1/users/me"
     "$BIN_DIR/email-sync" --account "$GMAIL_ACCT_A" 2>&1 || true)
}

# Helper: sync account B
run_gmail_sync_b() {
    (export XDG_CONFIG_HOME="$H_GMAIL/config"
     export XDG_DATA_HOME="$H_GMAIL/data"
     export XDG_CACHE_HOME="$H_GMAIL/cache"
     export HOME="$H_GMAIL"
     export GMAIL_TEST_TOKEN=testtoken2
     export GMAIL_API_BASE_URL="http://localhost:$GMAIL_PORT_B/gmail/v1/users/me"
     "$BIN_DIR/email-sync" --account "$GMAIL_ACCT_B" 2>&1 || true)
}

# Helper: read-only commands for account A
run_gmail_ro_a() {
    (export XDG_CONFIG_HOME="$H_GMAIL/config"
     export XDG_DATA_HOME="$H_GMAIL/data"
     export XDG_CACHE_HOME="$H_GMAIL/cache"
     export HOME="$H_GMAIL"
     export GMAIL_TEST_TOKEN=testtoken
     export GMAIL_API_BASE_URL="http://localhost:$GMAIL_PORT_A/gmail/v1/users/me"
     "$BIN_DIR/email-cli-ro" "$GMAIL_ACCT_A" "$@" 2>&1 || true)
}

# Helper: read-only commands for account B
run_gmail_ro_b() {
    (export XDG_CONFIG_HOME="$H_GMAIL/config"
     export XDG_DATA_HOME="$H_GMAIL/data"
     export XDG_CACHE_HOME="$H_GMAIL/cache"
     export HOME="$H_GMAIL"
     export GMAIL_TEST_TOKEN=testtoken2
     export GMAIL_API_BASE_URL="http://localhost:$GMAIL_PORT_B/gmail/v1/users/me"
     "$BIN_DIR/email-cli-ro" "$GMAIL_ACCT_B" "$@" 2>&1 || true)
}

# ── Gmail account A (test@gmail.com, 200 messages) ────────────────────────
# 26.1 Run email-sync for account A
SYNC26A=$(run_gmail_sync_a)
check "26.1 gmail-A sync: fetched messages" "fetched\|stored\|already" "$SYNC26A"

# 26.2 list --all --limit 200
GL_A=$(run_gmail_ro_a --batch list --all --limit 200)
check "26.2 gmail-A list: count shows messages" "message" "$GL_A"
check "26.3 gmail-A list: Message 1 present" "Message 1" "$GL_A"
check "26.4 gmail-A list: Message 200 present" "Message 200" "$GL_A"

# 26.5 show message 1
GS_A1=$(run_gmail_ro_a show 0000000000000001)
check "26.5 gmail-A show 1: subject present" "Message 1" "$GS_A1"
check "26.6 gmail-A show 1: sender present" "Sender 1" "$GS_A1"

# 26.7 show message 10 (has attachment)
GS_A10=$(run_gmail_ro_a show 000000000000000a)
check "26.7 gmail-A show 10: subject present" "Message 10" "$GS_A10"

# 26.8 list-attachments for message 10
GLA_A=$(run_gmail_ro_a --batch list-attachments 000000000000000a)
check "26.8 gmail-A list-attachments 10: notes_10.txt listed" "notes_10" "$GLA_A"

# 26.9 save-attachment for message 10
GSAVE_A_DIR="/tmp/email-cli-ft-gattach-a-$$"
mkdir -p "$GSAVE_A_DIR"
GSA_A=$(run_gmail_ro_a --batch save-attachment 000000000000000a notes_10.txt "$GSAVE_A_DIR")
check "26.9 gmail-A save-attachment: exit ok" "aved\|uccessful\|notes\|ok" "$GSA_A"
check "26.10 gmail-A save-attachment: file exists" "." \
    "$(test -f "$GSAVE_A_DIR/notes_10.txt" && echo ok || echo missing)"
rm -rf "$GSAVE_A_DIR"

# 26.11 list-folders account A
GF_A=$(run_gmail_ro_a --batch list-folders)
check "26.11 gmail-A list-folders: INBOX listed" "INBOX" "$GF_A"
check "26.12 gmail-A list-folders: Work listed" "Work" "$GF_A"

# ── Gmail account B (test2@gmail.com, 150 messages, prefix GmailB-) ───────
# 26.13 Sync account B
SYNC26B=$(run_gmail_sync_b)
check "26.13 gmail-B sync: fetched messages" "fetched\|stored\|already" "$SYNC26B"

# 26.14 list all 150 messages
GL_B=$(run_gmail_ro_b --batch list --all --limit 150)
check "26.14 gmail-B list: count shows messages" "message" "$GL_B"
check "26.15 gmail-B list: GmailB-Message 1 present" "GmailB-Message 1" "$GL_B"
check "26.16 gmail-B list: GmailB-Message 150 present" "GmailB-Message 150" "$GL_B"

# 26.17 show message 1 from account B
GS_B1=$(run_gmail_ro_b show 0000000000000001)
check "26.17 gmail-B show 1: subject has prefix" "GmailB-Message 1" "$GS_B1"
check "26.18 gmail-B show 1: sender present" "Sender 1" "$GS_B1"

# 26.19 show message 20 (has attachment, 20 % 10 == 0)
GS_B20=$(run_gmail_ro_b show 0000000000000014)
check "26.19 gmail-B show 20: correct subject" "GmailB-Message 20" "$GS_B20"

# 26.20 list-attachments for message 20
GLA_B=$(run_gmail_ro_b --batch list-attachments 0000000000000014)
check "26.20 gmail-B list-attachments 20: GmailB-notes_20.txt listed" "GmailB-notes_20" "$GLA_B"

# 26.21 save-attachment for message 20 (account B)
GSAVE_B_DIR="/tmp/email-cli-ft-gattach-b-$$"
mkdir -p "$GSAVE_B_DIR"
GSA_B=$(run_gmail_ro_b --batch save-attachment 0000000000000014 GmailB-notes_20.txt "$GSAVE_B_DIR")
check "26.21 gmail-B save-attachment: exit ok" "aved\|uccessful\|notes\|ok" "$GSA_B"
check "26.22 gmail-B save-attachment: file exists" "." \
    "$(test -f "$GSAVE_B_DIR/GmailB-notes_20.txt" && echo ok || echo missing)"
rm -rf "$GSAVE_B_DIR"

# ── Gmail cross-contamination checks ─────────────────────────────────────
# 26.23 Account A list must NOT contain account B's GmailB- prefix
check_not "26.23 gmail-A list: no GmailB- content" "GmailB-" "$GL_A"

# 26.24 Account B list must NOT contain account A's plain subjects
check_not "26.24 gmail-B list: subjects have prefix (no plain 'Message 1')" \
    "^.*[^-]Message 1$" "$GL_B"

# 26.25 Account A has 200 msgs; B's msg 150 ID (0000000000000096) not in A
GL_A_FULL=$(run_gmail_ro_a --batch list --all --limit 200)
check_not "26.25 gmail-A list: no GmailB-Message 150" "GmailB-Message 150" "$GL_A_FULL"

# 26.26 list-folders account B
GF_B=$(run_gmail_ro_b --batch list-folders)
check "26.26 gmail-B list-folders: INBOX listed" "INBOX" "$GF_B"

# Cleanup
kill "$GMAIL_SERVER_A_PID" "$GMAIL_SERVER_B_PID" 2>/dev/null || true
rm -rf "$H_GMAIL"

# ════════════════════════════════════════════════════════════════════════════
# Results
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Functional Test Results ---"
echo "Passed: $PASSED / $((PASSED + FAILED))"

if [ "$FAILED" -gt 0 ]; then
    echo "FUNCTIONAL TEST FAILED"
    exit 1
fi

echo "Functional test complete."
